export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const UPDATE_SELECTED_INDEX = 'UPDATE_SELECTED_INDEX'
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS'
